services:
  app:
    build: .
    command: npm run start:dev
    volumes:
      - .:/jo-send
    ports:
      - 3030:3030
    depends_on:
      - db
      - redis
      - solana-localnet
  
  db:
    image: mongo:latest
    restart: always
    volumes:
      - /data/db
    ports:
      - 27017:27017
  
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  
  solana-localnet:
    image: jolanalab/solana-node:latest
    command: solana-test-validator
    ports:
      - 8899:8899